### ISSUE TITLE
Ops-core FAST RAC headset doesn't seems to suppress sounds

### ISSUE THREAD

**Issue by Ninluc** [kobrakon/FirearmDeafen#1]
I don't know if it is intended, but when having the [Ops-core FAST RAC headset](https://escapefromtarkov.fandom.com/wiki/Ops-Core_FAST_RAC_Headset) equipped and shooting, I still get deafened.

**Comment by kobrakon** [comment]
version?

**Comment by Ninluc** [comment]
- SPT-AKI 3.4.1
- Same for mod version
- Tarkov 0.13

**Comment by kobrakon** [comment]
swear I fixed it, I'll check again and see what I can do when I get home

**Comment by Ninluc** [comment]
https://user-images.githubusercontent.com/56800521/212492304-8b70ff60-582b-41c9-8d3e-8b356824c702.mp4

I'll try to reinstall it later

**Comment by kobrakon** [comment]
yeah I saw during my own testing, just gonna have to figure a way to account for it

**Comment by kobrakon** [comment]
fixed in commit 81c52fba82e2e7da443272a42dfc460723c35917
